### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by algoflow19** [dmngu9/Voice-Activity-Detection#2]
I found this is a nice work!
But can you explain how to install and set Eigen3( I can't set it correctly, which has killed me hours...) correctly to work? It's just so hard for python-only  to compile this , and I just really want to see the result, thanks.

**Comment by dmngu9** [comment]
i dont maintain this repo anymore. But i think for eigen library. you dont need to install anything. i followed this instruction https://eigen.tuxfamily.org/dox/GettingStarted.html

**Comment by algoflow19** [comment]
Thanks, but when I did "make" after I did "cmake .." , I got this error:

Scanning dependencies of target vad
[ 50%] Building CXX object CMakeFiles/vad.dir/voice_detection.cpp.o
/home/caizerui/下载/Voice-Activity-Detection/voice_detection.cpp: In function ‘int main()’:
/home/caizerui/下载/Voice-Activity-Detection/voice_detection.cpp:91:24: error: no matching function for call to ‘std::basic_ofstream<char>::open(std::__cxx11::basic_stringstream<char>::__string_type)’
   myfile.open (ss.str());
                        ^
In file included from /home/caizerui/下载/Voice-Activity-Detection/voice_detection.cpp:8:0:
/usr/include/c++/5/fstream:799:7: note: candidate: void std::basic_ofstream<_CharT, _Traits>::open(const char*, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::_Ios_Openmode]
       open(const char* __s,
       ^
/usr/include/c++/5/fstream:799:7: note:   no known conversion for argument 1 from ‘std::__cxx11::basic_stringstream<char>::__string_type {aka std::__cxx11::basic_string<char>}’ to ‘const char*’
CMakeFiles/vad.dir/build.make:62: recipe for target 'CMakeFiles/vad.dir/voice_detection.cpp.o' failed
make[2]: *** [CMakeFiles/vad.dir/voice_detection.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/vad.dir/all' failed
make[1]: *** [CMakeFiles/vad.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I search google but I have no idea how to solve it, can you give me some advice? 

Update:( I install it in VM VirtualBox with ubuntu16.04 )

**Comment by isrish** [comment]
If you are using Ubuntu, you can install eigen3 or eigen2 by:`sudo apt-get install eigen2-dev eigen3-dev`

**Comment by algoflow19** [comment]
Thanks for your help!
It works!

**Comment by algoflow19** [comment]
Hi sir, I'm grateful for your help, and can you explain how to correctly run the program by updating the "voice_detection.cpp" , 
I just change the line 91 in "voice_detection.cpp" as you did and place a "sound.txt" in "/home/ngu11u/acoustic_ws/src/audioloc/src/3D/" showed in line 21 of "voice_detection.cpp" to make it work( I got the result by doing so ).
 How can I tell the program input file?( I a error by just updating the "voice_detection.cpp" after doing "../bin/./vad") @isrish 

The error:
vad: /usr/include/Eigen/src/Core/CwiseNullaryOp.h:74: Eigen::CwiseNullaryOp<NullaryOp, MatrixType>::CwiseNullaryOp(Eigen::Index, Eigen::Index, const NullaryOp&) [with NullaryOp = Eigen::internal::scalar_constant_op<double>; PlainObjectType = Eigen::Matrix<double, -1, 1>; Eigen::Index = long int]: Assertion `rows >= 0 && (RowsAtCompileTime == Dynamic || RowsAtCompileTime == rows) && cols >= 0 && (ColsAtCompileTime == Dynamic || ColsAtCompileTime == cols)' failed.
已放弃 (核心已转储)

^^^^^^^^^^^^^^^^^^^ it means "abandoned (core dump)"

**Comment by isrish** [comment]
you can try my fork. https://github.com/isrish/Voice-Activity-Detection
and run it `../bin/./vad your_audio_file.txt`

**Comment by algoflow19** [comment]
It works well, sir. Thanks a lot!  @isrish

**Comment by algoflow19** [comment]
Thank you!
I write down this to help others who also want to see the result.
Set Eigen:
Download Eigen3 and unzip it, then get a new folder , 
open it , mv "Eigen" to "usr/include" ( which is just my case with ubuntu 16.04 , in other case, you should find out where is your "include file" and do the same )
And: 
Need to "sudo install gnuplot-qt" or something else to use "gnuplot"

It also need you to learn a little about "gnuplot" to use it correctly.
