### ISSUE TITLE
what's the sample rate of the sound.txt ?

### ISSUE THREAD

**Issue by ucasiggcas** [dmngu9/Voice-Activity-Detection#7]
Dear,

What's the sr of the sound.txt ?
Thx

**Comment by huHHhhuhu** [comment]
Hi @ucasiggcas ,

Could you successfully run this project?
Did you use Eigen"3"?

Thanks!
David

**Comment by dmngu9** [comment]
yes, i can run it. I cant remember the sampling rate anymore
